org.gradle.jvmargs = -Xmx2048M

minecraft_version = 26.2
java_version = 25
enabled_platforms = fabric,neoforge
publish_artifact_task = shadowJar

archives_base_name = creepre_firework
mod_version = 3.0.0
maven_group = plus.dragons.creeprefirework

fabric_loader_version = 0.19.3
fabric_api_version = 0.156.0+26.2
neoforge_version = 26.2.0.42-beta
neoforge_version_range = [26.2.0.42-beta,)
minecraft_version_range = [26.2,26.3)

cloth_config_version = 26.2.155
mod_menu_version = 20.0.1

