org.gradle.jvmargs = -Xmx2048M

minecraft_version = 1.21.11
java_version = 21
enabled_platforms = fabric,neoforge
publish_artifact_task = remapJar

archives_base_name = creepre_firework
mod_version = 3.0.0
maven_group = plus.dragons.creeprefirework

yarn_mappings = 1.21.11+build.6
fabric_loader_version = 0.19.3
fabric_api_version = 0.141.6+1.21.11
neoforge_version = 21.11.45
yarn_mappings_patch_neoforge_version = 1.21+build.6
neoforge_version_range = [21.11.45,)
minecraft_version_range = [1.21.11,1.21.12)

cloth_config_version = 21.11.153
mod_menu_version = 17.0.0

