org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.21.4

archives_base_name=creepre_firework
mod_version=2.2.0
maven_group=plus.dragons.creeprefirework

yarn_mappings=1.21.4+build.8
fabric_loader_version=0.16.10
fabric_api_version=0.114.3+1.21.4
neoforge_version=21.4.58-beta
yarn_mappings_patch_neoforge_version=1.21+build.4

curseforge_id = 558439
modrinth_id = owUiXPam

