modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
[[mods]]
modId = "creeper_firework"
version = "${version}"
displayName="Creeper Firework" #mandatory
displayURL="https://github.com/DragonsPlusMinecraft/CreeperFirework" #optional
logoFile="icon.jpg" #optional
authors="MarbleGate" #optional
description='''
Creeper explodes into firework!
'''
[[dependencies.creeper_firework]] #optional
modId="neoforge" #mandatory
type = "required"
versionRange = "[21.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.creeper_firework]]
modId="minecraft"
type = "required"
versionRange = "[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="creeper_firework-common.mixins.json"