modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
[[mods]]
modId = "creeper_firework"
version = "${version}"
displayName="Creeper Firework" #mandatory
displayURL="https://github.com/DragonsPlusMinecraft/CreeperFirework" #optional
logoFile="icon.png" #optional
authors="MarbleGate" #optional
description='''
Creeper explodes into firework!
'''
[[dependencies.creeper_firework]] #optional
modId="neoforge" #mandatory
type = "required"
versionRange = "${neoforge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.creeper_firework]]
modId="minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[features.creeper_firework]
javaVersion="[${java_version},)"
[[mixins]]
config="creeper_firework-common.mixins.json"
